database:
  driver: postgres
  host: localhost
  port: 5432
  user: root
  password: root
  dbname: urldb
  ssl_mode: disable
  max_idle_conns: 5
  max_open_conns: 5

redis:
  address: localhost:6379
  password:
  db: 0

server:
  addr: ":8080"
  read_timeout: 5s
  write_timeout: 5s

app:
  base_url: "http://localhost:8080"
  default_duration: 10h
  cleanup_interval: 2h

shortcode:
  length: 6